eitango = {
     "Hello":"ハロー",
     "apple":"アップル",
     "book" : "ブック",
     "school":"スクール",
     "friend":"フレンド",
     "teacher": "ティーチャー",
     "study":"スタディ",
     "play":"プレイ",
     "eat":"イート",
     "happy":"ハッピー",
     "beautiful":"ビューティフル"}

eitango2 = {
    "Hello":"こんにちは",
    "apple":"りんご",
    "book" :"本",
    "school":"学校",
    "friend":"友達",
    "teacher":"先生",
    "study":"勉強",
    "play":"遊ぶ",
    "eat":"食べる",
    "happy":"幸せ",
    "beautiful":"美しい",
    "car":"車",
    "sleep":"寝る",
    "soccer":"サッカー",
    "bed":"ベッド",
    "dog":"犬",
    "doctor":"医者",
    "clock":"時計",
    "color":"色",
    "fish":"魚"}